<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10</LangVersion>
    <Version>2.0.6.1</Version>
    <DefineConstants>UNITY_STANDALONE_WIN</DefineConstants>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(UnityManagedDir)UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityManagedDir)UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(UnityManagedDir)UnityEngine.ScreenCaptureModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(UnityManagedDir)netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
